name: IPTV Ultra-Fast Auto Update

on:
  schedule:
    - cron: '0 */12 * * *' # প্রতি ১৫ মিনিট পর পর অটোমেটিক চলবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ৪0৩ এরর সমাধানের জন্য মাস্ট
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Deep Scanner
        run: python scanner.py

      - name: Commit and Push Update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Fuck-you-Ankita.m3u
          git commit -m "Auto Update: $(date)" || echo "No changes to commit"
          git push
