name: IPTV Ultra Scanner

on:
  schedule:
    - cron: '0 */12 * * *' # প্রতি ১২ ঘণ্টা পর পর অটো চলবে
  workflow_dispatch:      # আপনি চাইলে হাত দিয়েও রান করতে পারবেন

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Ultra Scanner
        run: python scanner.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add only_new_channels.m3u
          git commit -m "Auto update channels: $(date)" || echo "No changes to commit"
          git push
